name: squad
description: Open Source chat tool

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0

  cupertino_icons: ^1.0.2

  flutter_bloc: ^8.1.1

  equatable: ^2.0.5
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
